# Generated by Django 4.1.1 on 2022-09-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='especialista',
            field=models.CharField(default='Sim', max_length=4),
        ),
    ]
