# Generated by Django 4.1.1 on 2022-09-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0002_relatorio_especialista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorio',
            old_name='obs',
            new_name='responsaveis',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='clima',
            field=models.CharField(default='Joao', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatorio',
            name='temperatura',
            field=models.IntegerField(default=26),
            preserve_default=False,
        ),
    ]
