# Generated by Django 4.1.1 on 2022-09-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0003_rename_obs_relatorio_responsaveis_relatorio_clima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='altura',
            field=models.CharField(default='Sim', max_length=4),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='aterramento',
            field=models.CharField(default='Sim', max_length=4),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='auxconces',
            field=models.CharField(default='Sim', max_length=4),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='cinto_seg',
            field=models.CharField(default='Sim', max_length=4),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='conferido',
            field=models.CharField(default='Sim', max_length=4),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='curso_nr',
            field=models.CharField(default='Sim', max_length=4),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='delimitar_area',
            field=models.CharField(default='Sim', max_length=4),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='desligamento',
            field=models.CharField(default='Sim', max_length=4),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='dialogo',
            field=models.CharField(default='Sim', max_length=4),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='equipamentos',
            field=models.CharField(default='Sim', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='integridade',
            field=models.CharField(default='Sim', max_length=4),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='qualiprofi',
            field=models.CharField(default='Sim', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='reavaliacao',
            field=models.CharField(default='Sim', max_length=4),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='requi_seg',
            field=models.CharField(default='Sim', max_length=4),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='riscos',
            field=models.CharField(default='Sim', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='sinalizacao',
            field=models.CharField(default='Sim', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='tensao',
            field=models.CharField(default='Sim', max_length=4),
        ),
    ]
