# Generated by Django 4.1.1 on 2022-11-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0006_remove_relatorio_especialista_remove_relatorio_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='Qualificacao_Profissional',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='qualiprof',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='altura',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='aterramento',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='auxconces',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='cinto_seg',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='conferido',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='curso_nr',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='delimitar_area',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='desligamento',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='dialogo',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='equipamentos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='integridade',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='reavaliacao',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='requi_seg',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='riscos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='sinalizacao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='tensao',
            field=models.CharField(default='', max_length=4),
        ),
    ]
