# Generated by Django 4.1.1 on 2022-11-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0008_relatorio_altitude_relatorio_classestr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='documentacao',
            field=models.TextField(default='', max_length=100),
        ),
    ]
