# Generated by Django 4.1.1 on 2022-11-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0009_relatorio_documentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='documentacao',
            field=models.CharField(default='', max_length=100),
        ),
    ]
