# Generated by Django 4.1.1 on 2022-11-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0011_alter_relatorio_altitude_alter_relatorio_classestr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='advquadist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='ambientesofreu',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='barramentoquadist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='bitola',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='compinstalacao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='condutident',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='disjundif',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='dispprotecaoident',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='dispprotecaosurtos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='esqaterramento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='fontseguranca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='instalacaoinspecionada',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='instlquadist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='linhaseletricascorr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='linhaseletricasdisp',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='novoscircuitos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='paralelismo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='protcircuitos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='qtdesufitomadas',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='reservadeenergia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='servseguranca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='tomadasdeforca',
            field=models.CharField(default='', max_length=100),
        ),
    ]
