# Generated by Django 4.1.1 on 2022-11-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0013_relatorio_capbarramento_relatorio_continuidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='continuidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='ensaiodefunc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='ensaiodetensao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='resistencia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='selvpelv',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='verificacao',
            field=models.CharField(default='', max_length=100),
        ),
    ]
