# Generated by Django 4.1.1 on 2022-11-05 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0015_relatorio_circuito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='circuito',
        ),
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default='', max_length=100)),
                ('fase', models.CharField(default='', max_length=100)),
                ('disjuntor', models.CharField(default='', max_length=100)),
                ('descrição', models.CharField(default='', max_length=100)),
                ('condutor', models.CharField(default='', max_length=100)),
                ('corrente', models.CharField(default='', max_length=100)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.relatorio')),
            ],
        ),
    ]
