# Generated by Django 4.1.1 on 2022-11-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0016_remove_relatorio_circuito_circuito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuito',
            old_name='relatorio',
            new_name='rel_pai',
        ),
    ]
