# Generated by Django 4.1.1 on 2022-11-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0017_rename_relatorio_circuito_rel_pai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuito',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
