# Generated by Django 4.1.1 on 2022-11-09 14:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0021_alter_relatorio_equipamentos_alter_relatorio_riscos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
