# Generated by Django 4.1.1 on 2022-11-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0022_alter_imagens_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='condutor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='corrente',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='descricao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='disjuntor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='fase',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='modelo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='advquadist',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='altitude',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='ambientesofreu',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='barramentoquadist',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='bitola',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='classestr',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='clima',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='competencia',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='compinstalacao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='condambiente',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='condfuga',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='condutident',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='continuidade',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='contpessoas',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='descatm',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='disjundif',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='dispprotecaoident',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='dispprotecaosurtos',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='documentacao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='ensaiodefunc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='ensaiodetensao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='equipamentos',
            field=models.CharField(default='[]', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='esqaterramento',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='fontseguranca',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='infleletro',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='instalacaoinspecionada',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='instlquadist',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='linhaseletricascorr',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='linhaseletricasdisp',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='local',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='movdoar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='natmatcons',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='natmatpr',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='novoscircuitos',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='paralelismo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='presagua',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='presfauna',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='presmofo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='pressolidos',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='pressubst',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='protcircuitos',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='qtdesufitomadas',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='qualiprof',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='radsolar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='reseletr',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='reservadeenergia',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='resistencia',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='riscos',
            field=models.CharField(default='[]', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='selvpelv',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='servseguranca',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='sinalizacao',
            field=models.CharField(default='[]', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='solmecanicas',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='tempambiente',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='tomadasdeforca',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='vento',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='verificacao',
            field=models.CharField(default='', max_length=255),
        ),
    ]
